---
title: "EDA"
author: "Keshav"
date: "28 January 2018"
output: html_document
---
# Showing how EDA makes understanding of Missing value simple .The code is simple but powerful while understanding missing data.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("visdat")
library(visdat)

vis_dat(airquality)
```

```{r}
# We can sort the missing values in decreasing form.
vis_dat(airquality, 
        sort_type = FALSE)
```

```{r}
# Columns Data type and their missing values are also represnted.
vis_dat(typical_data)
```
```{r}
#By using vis_dat() we can look at many columns 
vis_dat(typical_data_large)
```

```{r}
#We can explore the missing data further using vis_miss().

vis_miss(airquality)
```
```{r}
# It will cluster missing Data for simple understanding.
vis_miss(airquality, 
         cluster = TRUE)
```
```{r}
#The columns can also just be arranged by columns with most missingness, by setting sort_miss = TRUE.

vis_miss(airquality,
         sort_miss = TRUE)
```

```{r}
#vis_miss indicates when there is a very small amount of missing data at <0.1% missingness.

test_miss_df <- data.frame(x1 = 1:10000,
                           x2 = rep("A", 10000),
                           x3 = c(rep(1L, 9999), NA))

vis_miss(test_miss_df)

```

```{r}
#vis_miss will also indicate when there is no missing data at all.
vis_miss(mtcars)
```

